"""Tests for deriving manifest location from an existing `repo`-tool workspace.

Builds real (tiny) git repos and real .repo/ layouts on disk rather than mocking git,
because every bug this module has had came from a mismatch between what `repo init`
actually writes to disk and what the code assumed it writes.
"""

from __future__ import annotations

import subprocess
import tempfile
import unittest
from pathlib import Path

from find_branch_repos.repo_workspace import (
    RepoWorkspaceError,
    make_submanifest_lookup,
    resolve_from_repo_dir,
)

GENERATED_STUB = """<?xml version="1.0" encoding="UTF-8"?>
<!--
DO NOT EDIT THIS FILE!  It is generated by repo and changes will be discarded.
-->
<manifest>
  <include name="{name}" />
</manifest>
"""


def _git(*args: str, cwd: Path) -> None:
    subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True)


class RepoWorkspaceTestBase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)

        # the "remote" manifest repo, with the root manifest in a subdirectory
        self.origin = self.root / "manifest_origin"
        self.origin.mkdir()
        _git("init", "-q", "-b", "main", ".", cwd=self.origin)
        _git("config", "user.email", "t@example.com", cwd=self.origin)
        _git("config", "user.name", "T", cwd=self.origin)
        (self.origin / "xml").mkdir()
        (self.origin / "xml" / "default.xml").write_text("<manifest/>")
        _git("add", "-A", cwd=self.origin)
        _git("commit", "-qm", "manifest", cwd=self.origin)

        # a `repo init`-style workspace: .repo/manifests is a checkout of the manifest repo on a
        # local branch named "default" that merely *tracks* the real manifest branch.
        self.workspace = self.root / "ws"
        self.repo_dir = self.workspace / ".repo"
        self.repo_dir.mkdir(parents=True)
        _git("clone", "-q", "--branch", "main", str(self.origin), str(self.repo_dir / "manifests"), cwd=self.root)
        manifests = self.repo_dir / "manifests"
        _git("branch", "-m", "default", cwd=manifests)
        _git("branch", "--set-upstream-to=origin/main", "default", cwd=manifests)

    def tearDown(self):
        self._tmp.cleanup()


class ManifestBranchTest(RepoWorkspaceTestBase):
    def test_reports_tracked_branch_not_local_default_branch(self):
        """`repo init` names the local branch "default"; the manifest branch is its upstream."""
        (self.repo_dir / "manifest.xml").write_text(GENERATED_STUB.format(name="xml/default.xml"))
        info = resolve_from_repo_dir(self.repo_dir)
        self.assertEqual(info.manifest_branch, "main")

    def test_falls_back_to_local_branch_name_without_upstream(self):
        manifests = self.repo_dir / "manifests"
        _git("branch", "--unset-upstream", "default", cwd=manifests)
        _git("branch", "-m", "release-2026", cwd=manifests)
        (self.repo_dir / "manifest.xml").write_text(GENERATED_STUB.format(name="xml/default.xml"))
        info = resolve_from_repo_dir(self.repo_dir)
        self.assertEqual(info.manifest_branch, "release-2026")

    def test_detached_head_raises(self):
        manifests = self.repo_dir / "manifests"
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=manifests, check=True, capture_output=True, text=True
        ).stdout.strip()
        _git("checkout", "-q", sha, cwd=manifests)
        (self.repo_dir / "manifest.xml").write_text(GENERATED_STUB.format(name="xml/default.xml"))
        with self.assertRaises(RepoWorkspaceError) as ctx:
            resolve_from_repo_dir(self.repo_dir)
        self.assertIn("--manifest-branch", str(ctx.exception))


class ManifestFileTest(RepoWorkspaceTestBase):
    def test_generated_stub_is_used_as_root_manifest_content(self):
        """Current repo versions write a real file with an <include>, not a symlink."""
        stub = GENERATED_STUB.format(name="xml/default.xml")
        (self.repo_dir / "manifest.xml").write_text(stub)
        info = resolve_from_repo_dir(self.repo_dir)
        self.assertIsNotNone(info.root_manifest_xml)
        self.assertIn(b'name="xml/default.xml"', info.root_manifest_xml)

    def test_symlink_keeps_subdirectory_prefix(self):
        """Older repo versions symlink into .repo/manifests/; the subdir must not be dropped."""
        (self.repo_dir / "manifest.xml").symlink_to("manifests/xml/default.xml")
        info = resolve_from_repo_dir(self.repo_dir)
        self.assertEqual(info.manifest_file, "xml/default.xml")
        self.assertIsNone(info.root_manifest_xml)

    def test_symlink_to_repo_root_file(self):
        (self.repo_dir / "manifests" / "default.xml").write_text("<manifest/>")
        (self.repo_dir / "manifest.xml").symlink_to("manifests/default.xml")
        info = resolve_from_repo_dir(self.repo_dir)
        self.assertEqual(info.manifest_file, "default.xml")

    def test_missing_manifest_xml_raises(self):
        with self.assertRaises(RepoWorkspaceError) as ctx:
            resolve_from_repo_dir(self.repo_dir)
        self.assertIn("--manifest-file", str(ctx.exception))

    def test_broken_symlink_raises(self):
        (self.repo_dir / "manifest.xml").symlink_to("manifests/does-not-exist.xml")
        with self.assertRaises(RepoWorkspaceError):
            resolve_from_repo_dir(self.repo_dir)


class WorkspaceLayoutTest(RepoWorkspaceTestBase):
    def setUp(self):
        super().setUp()
        (self.repo_dir / "manifest.xml").write_text(GENERATED_STUB.format(name="xml/default.xml"))

    def test_accepts_workspace_root_as_well_as_repo_dir(self):
        from_repo_dir = resolve_from_repo_dir(self.repo_dir)
        from_workspace = resolve_from_repo_dir(self.workspace)
        self.assertEqual(from_repo_dir, from_workspace)

    def test_manifest_url_comes_from_manifests_remote(self):
        info = resolve_from_repo_dir(self.repo_dir)
        self.assertEqual(info.manifest_url, str(self.origin))

    def test_local_manifests_dir_detected_when_present(self):
        self.assertIsNone(resolve_from_repo_dir(self.repo_dir).local_manifest_dir)
        (self.repo_dir / "local_manifests").mkdir()
        self.assertEqual(
            resolve_from_repo_dir(self.repo_dir).local_manifest_dir,
            str(self.repo_dir / "local_manifests"),
        )

    def test_directory_without_repo_dir_raises(self):
        with self.assertRaises(RepoWorkspaceError):
            resolve_from_repo_dir(self.root / "manifest_origin")

    def test_repo_dir_without_manifests_checkout_raises(self):
        bare = self.root / "empty_ws" / ".repo"
        bare.mkdir(parents=True)
        with self.assertRaises(RepoWorkspaceError) as ctx:
            resolve_from_repo_dir(bare)
        self.assertIn("repo init", str(ctx.exception))


class SubmanifestLookupTest(RepoWorkspaceTestBase):
    """`repo sync` puts submanifest checkouts at .repo/submanifests/<path>/manifests/."""

    def test_reads_checked_out_submanifest(self):
        checkout = self.repo_dir / "submanifests" / "vendor" / "manifests"
        checkout.mkdir(parents=True)
        (checkout / "default.xml").write_bytes(b"<manifest/>")

        lookup = make_submanifest_lookup(self.repo_dir)
        self.assertEqual(lookup("vendor", "default.xml"), b"<manifest/>")

    def test_returns_none_when_not_checked_out(self):
        lookup = make_submanifest_lookup(self.repo_dir)
        self.assertIsNone(lookup("vendor", "default.xml"))
        self.assertIsNone(lookup("", ""))

    def test_nested_submanifest_path(self):
        checkout = self.repo_dir / "submanifests" / "outer" / "inner" / "manifests"
        checkout.mkdir(parents=True)
        (checkout / "sub.xml").write_bytes(b"<manifest/>")

        lookup = make_submanifest_lookup(self.repo_dir)
        self.assertEqual(lookup("outer/inner", "sub.xml"), b"<manifest/>")

    def test_does_not_escape_the_submanifest_checkout(self):
        checkout = self.repo_dir / "submanifests" / "vendor" / "manifests"
        checkout.mkdir(parents=True)
        (self.repo_dir / "secret.xml").write_bytes(b"<manifest/>")

        lookup = make_submanifest_lookup(self.repo_dir)
        self.assertIsNone(lookup("vendor", "../../../secret.xml"))


if __name__ == "__main__":
    unittest.main()
